version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5657:80'
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: colocDB
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
